from selenium import webdriver
from selenium.webdriver.common.by import By
import time;

navegador = webdriver.Chrome()

navegador.get("https://sistema-1-login.netlify.app/")
time.sleep(1)
navegador.maximize_window()
time.sleep(1)
navegador.find_element(By.ID, "goRegister").click()
time.sleep(1)
navegador.find_element(By.ID, "name").send_keys("cesar")
time.sleep(1)
navegador.find_element(By.ID, "email").send_keys("cesar@gmail.com")
time.sleep(1)
navegador.find_element(By.ID, "password").send_keys("Cesar1231")
time.sleep(1)
navegador.find_element(By.ID, "confirmPassword").send_keys("Cesar1231")
time.sleep(1)
navegador.find_element(By.ID, "terms").click()
time.sleep(1)
navegador.find_element(By.ID, "createAccountButton").click()
time.sleep(1)
navegador.find_element(By.ID, "goLogin").click()
time.sleep(1)
navegador.find_element(By.ID, "email").send_keys("cesar@gmail.com")
time.sleep(1)
navegador.find_element(By.ID, "password").send_keys("Cesar1231")
time.sleep(1)
navegador.find_element(By.ID, "loginButton").click()
time.sleep(1)
# navegador.switch_to.alert.accept()
navegador.find_elements(By.XPATH, "//button[contains(., 'Excluir' )]")[0].click()
time.sleep(1)
navegador.switch_to.alert.accept()
navegador.find_elements(By.XPATH, "//button[contains(., 'Excluir')]")[0].click()
time.sleep(1)
navegador.switch_to.alert.accept()
time.sleep(1)
navegador.save_screenshot("print.png")
time.sleep(1)
navegador.find_element(By.ID, "logoutButton").click()
time.sleep(1000)