describe('Teste completo', () => {
    it('Cenário de teste completo', () => {

        cy.visit("https://banco-fake.netlify.app/")
        cy.wait(1000)
        cy.get("#inputRegisterName").type("cesar")
        cy.wait(1000)
        cy.get("#inputRegisterEmail").type("cesar@gmail.com")
        cy.wait(1000)
        cy.get("#inputRegisterPassword").type("cesar123.com")
        cy.wait(1000)
        cy.get("#btnCreateAccount").click()
        cy.wait(1000)
        cy.get("#btnGoToLogin").click()
        cy.wait(1000)
        cy.get("#inputLoginEmail").type("cesar@gmail.com")
        cy.wait(1000)
        cy.get("#inputLoginPassword").type("cesar123.com")
        cy.wait(1000)
        cy.get("#btnLogin").click()
        cy.wait(1000)
        cy.get("#tabDepositar").click()
        cy.wait(1000)
        cy.get("#inputDeposito").type("1000")
        cy.wait(1000)
        cy.get("#btnDepositar").click()
        cy.wait(1000)
        cy.get("#tabSacar").click()
        cy.wait(1000)
        cy.get("#inputSaque").type("500")
        cy.wait(1000)
        cy.get("#btnSacar").click()
        cy.wait(1000)
        cy.get("#tabSaldo").click()
        cy.wait(1000)
        cy.get("#tabLogout").click()
    });
});